name: Build and Deploy to AKS

on:
  push:
    branches:
      - master   # adjust branch as needed

env:
  REGISTRY_NAME: dockerk8sdemoapiapp20250919115743          # ACR name (without .azurecr.io)
  IMAGE_NAME: dockerk8sdemoapiapp                 # image repo name
  RESOURCE_GROUP: rg-miniAPI-demo             # AKS resource group
  CLUSTER_NAME: mini-API-demo      # AKS cluster name
  CLUSTER_RESOURCE_GROUP: k8s-group
  NAMESPACE: default                  # or your target namespace

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        ### Create a Service Principal with secret:
        # az ad sp create-for-rbac \
        # --name "gh-actions" \
        # --role AcrPush \
        # --scopes $(az acr show --name <cluster-name> --query id -o tsv)

    - name: Log in to ACR
      run: |
        az acr login --name $REGISTRY_NAME

    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./DockerK8sDemo.APIApp/Dockerfile
        push: true
        tags: ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest

    # - name: Export IMAGE_TAG
    #   run: echo "IMAGE_TAG=latest" >> $GITHUB_ENV

    # - name: Debug IMAGE_TAG
    #   run: echo "IMAGE_TAG=${{ env.IMAGE_TAG }}"

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
        cluster-name: ${{ env.CLUSTER_NAME }}
        
    - name: Deploy manifest
      run: |
        kubectl apply -f manifests/deployment.yaml
        kubectl apply -f manifests/service.yaml
        kubectl rollout status deployment dockerk8sdemoapiapp



    # - name: Deploy to AKS
    #   run: |
    #     kubectl set image deployment/dockerk8sdemoapiapp dockerk8sdemoapiapp=$REGISTRY_NAME.azurecr.io/$IMAGE_NAME:${{ env.IMAGE_TAG }} -n $NAMESPACE
    #     kubectl rollout status deployment/dockerk8sdemoapiapp -n $NAMESPACE

